[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/sheets"
  to = "/.netlify/functions/sheets"
  status = 200

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
